### ISSUE TITLE
 May I help in maintaining and releasing this doc?

### ISSUE THREAD

**Issue by mapleFU** [tangwz/db-monthly#1]
Hi @tangwz !

It seems this repo has no releases from the few months later, while there are still several inflight blogs(rename to PolarDB database monthly). I'm willing to help in maintaining and releasing this doc. Do you have some suggestions how we can collaborate in this direction?

**Comment by tangwz** [comment]
Why not submit a PR? I'll merge the PR if necessary.

**Comment by mapleFU** [comment]
Seems that the posts these months is submit. Next time maybe I'll submit a pr for this. Thanks!
