### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by shaohk** [tangwz/db-monthly#3]
这个分类的目录还有在维护吗？能否更新一下？
另外，列表里的标题，能否加上是哪一期的？

**Comment by vimiix** [comment]
@shaohk  写了个 wrapper 可以看下 https://alidbmonthly.vimiix.com/

**Comment by tangwz** [comment]
@shaohk 已经更新了，后续可以考虑下加上
@vimiix 这是个不错的方式，可以参考下吗？

**Comment by vimiix** [comment]
> @vimiix 这是个不错的方式，可以参考下吗？

@tangwz  代码在这里 https://github.com/vimiix/ali-db-monthly
